name: Deploy HML

on:
  push:
    branches: [develop]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  deploy:
    name: Deploy para Homologação (porta 9000)
    runs-on: self-hosted
    needs: ci
    environment: homologacao
    steps:
      - name: Deploy HML
        working-directory: /home/univates/receitas-app
        run: |
          set -e
          git fetch origin develop
          git reset --hard origin/develop
          docker compose -f docker-compose.hml.yml up --build -d
          echo "HML atualizado com sucesso"
          docker compose -f docker-compose.hml.yml ps
        env:
          HML_JWT_SECRET: ${{ secrets.HML_JWT_SECRET }}
